### PR TITLE
HELM-95: Expose Resource Label attribute to Grafana variables

### PR DESCRIPTION
**Pull request by jeffgdotorg**
Added a "text" property, populated with resource.label, to results

# Pull Request Check Sheet

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [x] If this is a new feature, is there documentation?
* [ ] If this is a new feature or substantial change, are there tests that cover it?

# Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

# External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-95
* Continuous Integration: [Bamboo](https://bamboo.opennms.org/), [CircleCI](https://circleci.com/gh/OpenNMS/opennms-js)

### CODE REVIEW

**Review by RangerRick — APPROVED** [review]
Seems pretty straightforward...

**Comment by j-white** [comment]
Dino raises a good point in the JIRA - the regex works on the name, but with this it is no longer displayed

**Comment by jeffgdotorg** [comment]
> Dino raises a good point in the JIRA - the regex works on the name, but with this it is no longer displayed

Latest commit makes the default behavior backward-compatible, and provides a way to flip between seeing labels and seeing IDs.

**Comment by dino2gnt** [comment]
Love it. :+1:

**Comment by RangerRick** [comment]
Nice, LGTM

**Pull request merged**
