### PR TITLE
HELM-184: pass metadata through in a way that is compatible with 6.4

### PR DESCRIPTION
**Pull request by RangerRick**
This PR fixes the entity datasource to pass alarm and node data in a way that won't get eaten by Grafana's recent data backend refactor.  It also includes a few changes to the way `lodash` is pulled in to reduce the amount of code referenced at runtime.

Grafana's `TableData` datatype _does_ actually have a `meta` property that is not destroyed when "legacy" table data is passed through Grafana 6.4's updates, and it _appears_ to be backwards-compatible with older Grafana 6 releases.

Originally I planned to convert our datasources to use the newer `DataFrame` APIs provided by `@grafana/data` and `@grafana/ui` but they've made it clear those APIs are alpha and could change at any time, so I decided to go the safe route and rearrange the code to store in the existing `meta` slot instead.

# Pull Request Check Sheet

* [x] Have you read and followed our [Contribution Guidelines](https://github.com/OpenNMS/opennms/blob/develop/CONTRIBUTING.md)?
* [x] Have you [made an issue in the OpenNMS issue tracker](https://issues.opennms.org)?<br>If so, you should:
  1. update the title of this PR to be of the format: `${JIRA-ISSUE-NUMBER}: subject of pull request`
  2. update the JIRA link at the bottom of this comment to refer to the real issue number
  3. prefix your commit messages with the issue number, if possible
* [x] Have you made a comment in that issue which points back to this PR?
* [x] Have you updated the JIRA link at the bottom of this comment to link to your issue?
* [x] If this is a new feature, is there documentation?
* [x] If this is a new feature or substantial change, are there tests that cover it?

# Pull Request Process

One or more reviewers should be assigned to each PR.

If you know that a particular person is subject matter expert in the area your PR affects, feel free to assign one or more reviewers when you create this PR, otherwise reviewers will be assigned for you.

Once the reviewer(s) accept the PR and the branch passes continuous integration in Bamboo, the PR is eligible for merge.

At that time, if you have commit access (are an OpenNMS Group employee or a member of the Order of the Green Polo) you are welcome to merge the PR.
Otherwise, a reviewer can merge it for you.

Thanks for taking time to contribute!

# External References

* JIRA (Issue Tracker): http://issues.opennms.org/browse/HELM-184
* Continuous Integration: [Bamboo](https://bamboo.opennms.org/), [CircleCI](https://circleci.com/gh/OpenNMS/opennms-js)

### CODE REVIEW

**Comment by indigo423** [comment]
Can we bump with this PR the version for the Grafana base image to 4.0?

**Comment by j-white** [comment]
Looks OK. The lodash refactoring should have been done separately though - seems like unnecessary churn right now.

**Comment by RangerRick** [comment]
> Looks OK. The lodash refactoring should have been done separately though - seems like unnecessary churn right now.

True, I can undo it, I've just been trying to clean those up as I see them.  I'll move it to a separate PR.

**Comment by RangerRick** [comment]
I moved the lodash changes and a few other cleanups to https://github.com/OpenNMS/opennms-helm/tree/ranger/lodash-and-cleanup so this branch should be pretty minimal now.

**Pull request merged**
