### PR TITLE
HELM-88: fix PM datasource failure handling

### PR DESCRIPTION
**Pull request by RangerRick**
This PR fixes the PM datasource to properly return a rejection when the request fails.  It also tweaks the failure object so it provides a bit more data in the inspector.

### CODE REVIEW

**Comment by j-white** [comment]
On timeout, I now get a message in the console:
   `Panel request cancelled {err: {…}, cancelled: true, message: "An unexpected error occurred."}`
but the Graph panel keeps spinning.

Did you observe different behavior?

**Comment by RangerRick** [comment]
Hm, I do observe different behavior.

It doesn't spin for me, and it doesn't show as cancelled.  Instead, when I stop my OpenNMS I get:

```
Panel data error: {data: "", status: 502, headers: ƒ, config: {…}, statusText: "Bad Gateway", …}
```

What browser/OpenNMS version/resources/attributes?  Also, do you see any data in the inspector?

**Comment by RangerRick** [comment]
Ah yeah, I get you.  I'll see if I can come up with something listening on 8980 that never responds and try to reproduce your issue.

**Comment by RangerRick** [comment]
Aha, if the `cancelled` property is on the object, it never finishes.  I've pushed an updated version that seems to handle it right for me.  Can you confirm?

**Comment by j-white** [comment]
Works much better now.

**Pull request merged**
