### PR TITLE
HELM-377: Remove Angular Code

### PR DESCRIPTION
**Pull request by synqotik**
Remove all Angular code from HELM.

Rename the React datasources and panels to not have `React` or `-react`.

Rebased off latest feature branch, after `develop` was merged in.

There are some SonarCloud security and other issues, we will address them separately as they refer to code that was already in the codebase.

# External References

* JIRA (Issue Tracker): https://opennms.atlassian.net/browse/HELM-377
* Continuous Integration: [CircleCI](https://circleci.com/gh/OpenNMS/opennms-helm)

### CODE REVIEW

**Comment by synqotik** [comment]
Need to fix the SonarCloud items and then also rebase to get latest bug fixes.

**Comment by RangerRick** [comment]
@synqotik

Sonar's complaints about this are probably valid. What kind of thing are you trying to parse out with this?

```typescript
    { name: FlowTemplateVariablesStrings.interfacesOnExporterNodeWithFlows, expression: /interfacesOnExporterNodeWithFlows\(\s*([^,]+).*\)/
```

...That's going to match 0 or more spaces, anything that's not a comma greedily, but then also anything else, greedily. Is it always gonna be something with more than one argument? (ie, at least one comma?)

If so, you could do this to make it a little less CPU-intensive:

```typescript
    { name: FlowTemplateVariablesStrings.interfacesOnExporterNodeWithFlows, expression: /interfacesOnExporterNodeWithFlows\(\s*([^,]+),[^\)]+\)/
```

or, if it can either be a single argument _or_ one with a comma, you probably need to do a bit more work.

Either way, for things that are matching `foo(blahblah)` I really like using `[^\)]+` to match everything up to the closing paren. That limits the amount of work the regex engine has to do rather than looking for "anything" and trying to backtrack.

**Comment by synqotik** [comment]
> @synqotik
> 
> Sonar's complaints about this are probably valid. What kind of thing are you trying to parse out with this?


This wasn't code I touched, I suspect Sonar is analyzing it now since things have been renamed. I will take a look at your suggestion and make a fix.

**Comment by RangerRick** [comment]
> > @synqotik
> > Sonar's complaints about this are probably valid. What kind of thing are you trying to parse out with this?
> 
> This wasn't code I touched, I suspect Sonar is analyzing it now since things have been renamed. I will take a look at your suggestion and make a fix.

Ah, alright, well if sonar blocks merging, I can do it as an admin. Probably still worth fixing though. :D

**Review by aramosvizcarra — APPROVED** [review]
Looks great!

**Review by RangerRick — APPROVED** [review]

**Pull request merged**
