### PR TITLE
Colorize alarm details header with alarm's severity

### PR DESCRIPTION
**Pull request by mvrueden**
I had this idea of not showing the alarm severity but colorize the header with the alarm's severity.

Feel free to merge or reject (-:
If it gets accepted, I can still create an issue for it.

### CODE REVIEW

**Comment by jeffgdotorg** [comment]
Maybe hover to reveal the textual severity? Thinking about users with screen readers.

**Comment by mvrueden** [comment]
@jeffgdotorg  If you hover over the icon, the textual representation is shown.

**Comment by j-white** [comment]
This looks odd to me.

image

**Comment by mvrueden** [comment]
Considering this as rejected. Closing (-:

**Pull request closed without merging**
