### PR TITLE
HELM-63: allow reordering of elements

### PR DESCRIPTION
**Pull request by RangerRick**
Add support for reordering columns in the alarm table config.

### CODE REVIEW

**Comment by smith-opennms** [comment]
LGTM

**Comment by j-white** [comment]
The header of the table get immediately updated after the columns have been re-ordered, but the body of the table isn't updated accordingly until the panel is refresh.

Is it feasible to make the body of the table update immediately too?

**Comment by RangerRick** [comment]
@j-white hrm, good question, I'll see if I can trigger a re-render

**Comment by RangerRick** [comment]
Yup, just needed to re-render the panel after the columns changed and it fixed it.

**Pull request merged**
