### PR TITLE
NMS-13374: Implement to show aggregation display on Grafana using data from Cortex

### PR DESCRIPTION
**Pull request by swachter**
issue: https://issues.opennms.org/browse/NMS-13374

This PR adds "Cortex Flow Deep Dive" dashboard to the helm plugin that is similar to the existing "Flow Deep Dive" dashboard but gets all its data directly from Cortex.

The linked issue contains information how the environment can be setup to review this PR.

### CODE REVIEW

**Review by fooker — APPROVED** [review]
I don't have a setup to test this with some real data right now.
Technical, this looks sane.

Let's correct the title of the PR and push it out to get some feedback from users.

**Comment by RangerRick** [comment]
Yeah, I'm setting up test stuff and will play with it today.

**Comment by RangerRick** [comment]
Hrm, I'm trying to test this using your branch and I'm not sure how to actually _add_ your cortex dashboard. When I go to Helm in my Grafana I only see the other 2.

Screen Shot 2021-09-20 at 3 03 33 PM

I confirmed my `dist/` directory contains the right stuff (`plugin.json` has your cortex line, and the dashboard exists too)

Was there anything weird you had to do to make this work in testing?

**Comment by swachter** [comment]
I checked with fresh installs of Grafana 7.5.10 and 8.1.4. I found that maybe the dashboard `id` that was assigned in `cortex_flow_deep_dive.json` causes troubles. After having `"id"=null` in `cortex_flow_deep_dive.json` (like the existing Flow Deep Dive dashboard has), I could load the dashboard into the fresh installs.

**Review by RangerRick — APPROVED** [review]
Looks like it was a particular problem with grafana `8.0.6`, upgrading made it work.  Looks great!

Screen Shot 2021-09-21 at 11 45 58 AM

**Pull request merged**
